augment2d:
  gridmask:
    fixed_prob: true
    prob: 0.0
  resize:
  - - 0.38
    - 0.55
  - - 0.48
    - 0.48
  rotate:
  - -5.4
  - 5.4
augment3d:
  rotate:
  - -0.78539816
  - 0.78539816
  scale:
  - 0.9
  - 1.1
  translate: 0.5
checkpoint_config:
  interval: 1
  max_keep_ckpts: 1
cudnn_benchmark: false
data:
  samples_per_gpu: 2
  test:
    ann_file: data/nuscenes/nuscenes_infos_val.pkl
    box_type_3d: LiDAR
    dataset_root: data/nuscenes/
    map_classes:
    - drivable_area
    - ped_crossing
    - walkway
    - stop_line
    - carpark_area
    - divider
    modality:
      use_camera: true
      use_external: false
      use_lidar: true
      use_map: false
      use_radar: false
    object_classes:
    - car
    - truck
    - construction_vehicle
    - bus
    - trailer
    - barrier
    - motorcycle
    - bicycle
    - pedestrian
    - traffic_cone
    pipeline:
    - to_float32: true
      type: LoadMultiViewImageFromFiles
    - coord_type: LIDAR
      load_augmented: null
      load_dim: 5
      reduce_beams: 32
      type: LoadPointsFromFile
      use_dim: 5
    - load_augmented: null
      load_dim: 5
      pad_empty_sweeps: true
      reduce_beams: 32
      remove_close: true
      sweeps_num: 9
      type: LoadPointsFromMultiSweeps
      use_dim: 5
    - type: LoadAnnotations3D
      with_attr_label: false
      with_bbox_3d: true
      with_label_3d: true
    - bot_pct_lim:
      - 0.0
      - 0.0
      final_dim:
      - 256
      - 704
      is_train: false
      rand_flip: false
      resize_lim:
      - 0.48
      - 0.48
      rot_lim:
      - 0.0
      - 0.0
      type: ImageAug3D
    - is_train: false
      resize_lim:
      - 1.0
      - 1.0
      rot_lim:
      - 0.0
      - 0.0
      trans_lim: 0.0
      type: GlobalRotScaleTrans
    - classes:
      - drivable_area
      - ped_crossing
      - walkway
      - stop_line
      - carpark_area
      - divider
      dataset_root: data/nuscenes/
      type: LoadBEVSegmentation
      xbound:
      - -50.0
      - 50.0
      - 0.5
      ybound:
      - -50.0
      - 50.0
      - 0.5
    - point_cloud_range:
      - -51.2
      - -51.2
      - -5.0
      - 51.2
      - 51.2
      - 3.0
      type: PointsRangeFilter
    - mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      type: ImageNormalize
    - classes:
      - car
      - truck
      - construction_vehicle
      - bus
      - trailer
      - barrier
      - motorcycle
      - bicycle
      - pedestrian
      - traffic_cone
      type: DefaultFormatBundle3D
    - keys:
      - img
      - points
      - gt_bboxes_3d
      - gt_labels_3d
      - gt_masks_bev
      meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix
      type: Collect3D
    test_mode: true
    type: NuScenesDataset
  train:
    dataset:
      ann_file: data/nuscenes/nuscenes_infos_train.pkl
      box_type_3d: LiDAR
      dataset_root: data/nuscenes/
      map_classes:
      - drivable_area
      - ped_crossing
      - walkway
      - stop_line
      - carpark_area
      - divider
      modality:
        use_camera: true
        use_external: false
        use_lidar: true
        use_map: false
        use_radar: false
      object_classes:
      - car
      - truck
      - construction_vehicle
      - bus
      - trailer
      - barrier
      - motorcycle
      - bicycle
      - pedestrian
      - traffic_cone
      pipeline:
      - to_float32: true
        type: LoadMultiViewImageFromFiles
      - coord_type: LIDAR
        load_augmented: null
        load_dim: 5
        reduce_beams: 32
        type: LoadPointsFromFile
        use_dim: 5
      - load_augmented: null
        load_dim: 5
        pad_empty_sweeps: true
        reduce_beams: 32
        remove_close: true
        sweeps_num: 9
        type: LoadPointsFromMultiSweeps
        use_dim: 5
      - type: LoadAnnotations3D
        with_attr_label: false
        with_bbox_3d: true
        with_label_3d: true
      - db_sampler:
          classes:
          - car
          - truck
          - construction_vehicle
          - bus
          - trailer
          - barrier
          - motorcycle
          - bicycle
          - pedestrian
          - traffic_cone
          dataset_root: data/nuscenes/
          info_path: data/nuscenes/nuscenes_dbinfos_train.pkl
          points_loader:
            coord_type: LIDAR
            load_dim: 5
            reduce_beams: ${reduce_beams
            type: LoadPointsFromFile
            use_dim: 5
          prepare:
            filter_by_difficulty:
            - -1
            filter_by_min_points:
              barrier: 5
              bicycle: 5
              bus: 5
              car: 5
              construction_vehicle: 5
              motorcycle: 5
              pedestrian: 5
              traffic_cone: 5
              trailer: 5
              truck: 5
          rate: 1.0
          sample_groups:
            barrier: 2
            bicycle: 6
            bus: 4
            car: 2
            construction_vehicle: 7
            motorcycle: 6
            pedestrian: 2
            traffic_cone: 2
            trailer: 6
            truck: 3
        stop_epoch: -1
        type: ObjectPaste
      - bot_pct_lim:
        - 0.0
        - 0.0
        final_dim:
        - 256
        - 704
        is_train: true
        rand_flip: true
        resize_lim:
        - 0.38
        - 0.55
        rot_lim:
        - -5.4
        - 5.4
        type: ImageAug3D
      - is_train: true
        resize_lim:
        - 0.9
        - 1.1
        rot_lim:
        - -0.78539816
        - 0.78539816
        trans_lim: 0.5
        type: GlobalRotScaleTrans
      - classes:
        - drivable_area
        - ped_crossing
        - walkway
        - stop_line
        - carpark_area
        - divider
        dataset_root: data/nuscenes/
        type: LoadBEVSegmentation
        xbound:
        - -50.0
        - 50.0
        - 0.5
        ybound:
        - -50.0
        - 50.0
        - 0.5
      - type: RandomFlip3D
      - point_cloud_range:
        - -51.2
        - -51.2
        - -5.0
        - 51.2
        - 51.2
        - 3.0
        type: PointsRangeFilter
      - point_cloud_range:
        - -51.2
        - -51.2
        - -5.0
        - 51.2
        - 51.2
        - 3.0
        type: ObjectRangeFilter
      - classes:
        - car
        - truck
        - construction_vehicle
        - bus
        - trailer
        - barrier
        - motorcycle
        - bicycle
        - pedestrian
        - traffic_cone
        type: ObjectNameFilter
      - mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        type: ImageNormalize
      - fixed_prob: true
        max_epoch: 20
        mode: 1
        offset: false
        prob: 0.0
        ratio: 0.5
        rotate: 1
        type: GridMask
        use_h: true
        use_w: true
      - type: PointShuffle
      - classes:
        - car
        - truck
        - construction_vehicle
        - bus
        - trailer
        - barrier
        - motorcycle
        - bicycle
        - pedestrian
        - traffic_cone
        type: DefaultFormatBundle3D
      - keys:
        - img
        - points
        - gt_bboxes_3d
        - gt_labels_3d
        - gt_masks_bev
        meta_keys:
        - camera_intrinsics
        - camera2ego
        - lidar2ego
        - lidar2camera
        - camera2lidar
        - lidar2image
        - img_aug_matrix
        - lidar_aug_matrix
        type: Collect3D
      test_mode: false
      type: NuScenesDataset
      use_valid_flag: true
    type: CBGSDataset
  val:
    ann_file: data/nuscenes/nuscenes_infos_val.pkl
    box_type_3d: LiDAR
    dataset_root: data/nuscenes/
    map_classes:
    - drivable_area
    - ped_crossing
    - walkway
    - stop_line
    - carpark_area
    - divider
    modality:
      use_camera: true
      use_external: false
      use_lidar: true
      use_map: false
      use_radar: false
    object_classes:
    - car
    - truck
    - construction_vehicle
    - bus
    - trailer
    - barrier
    - motorcycle
    - bicycle
    - pedestrian
    - traffic_cone
    pipeline:
    - to_float32: true
      type: LoadMultiViewImageFromFiles
    - coord_type: LIDAR
      load_augmented: null
      load_dim: 5
      reduce_beams: 32
      type: LoadPointsFromFile
      use_dim: 5
    - load_augmented: null
      load_dim: 5
      pad_empty_sweeps: true
      reduce_beams: 32
      remove_close: true
      sweeps_num: 9
      type: LoadPointsFromMultiSweeps
      use_dim: 5
    - type: LoadAnnotations3D
      with_attr_label: false
      with_bbox_3d: true
      with_label_3d: true
    - bot_pct_lim:
      - 0.0
      - 0.0
      final_dim:
      - 256
      - 704
      is_train: false
      rand_flip: false
      resize_lim:
      - 0.48
      - 0.48
      rot_lim:
      - 0.0
      - 0.0
      type: ImageAug3D
    - is_train: false
      resize_lim:
      - 1.0
      - 1.0
      rot_lim:
      - 0.0
      - 0.0
      trans_lim: 0.0
      type: GlobalRotScaleTrans
    - classes:
      - drivable_area
      - ped_crossing
      - walkway
      - stop_line
      - carpark_area
      - divider
      dataset_root: data/nuscenes/
      type: LoadBEVSegmentation
      xbound:
      - -50.0
      - 50.0
      - 0.5
      ybound:
      - -50.0
      - 50.0
      - 0.5
    - point_cloud_range:
      - -51.2
      - -51.2
      - -5.0
      - 51.2
      - 51.2
      - 3.0
      type: PointsRangeFilter
    - mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      type: ImageNormalize
    - classes:
      - car
      - truck
      - construction_vehicle
      - bus
      - trailer
      - barrier
      - motorcycle
      - bicycle
      - pedestrian
      - traffic_cone
      type: DefaultFormatBundle3D
    - keys:
      - img
      - points
      - gt_bboxes_3d
      - gt_labels_3d
      - gt_masks_bev
      meta_keys:
      - camera_intrinsics
      - camera2ego
      - lidar2ego
      - lidar2camera
      - camera2lidar
      - lidar2image
      - img_aug_matrix
      - lidar_aug_matrix
      type: Collect3D
    test_mode: false
    type: NuScenesDataset
  workers_per_gpu: 1
dataset_root: data/nuscenes/
dataset_type: NuScenesDataset
deterministic: false
evaluation:
  interval: 1
  pipeline:
  - to_float32: true
    type: LoadMultiViewImageFromFiles
  - coord_type: LIDAR
    load_augmented: null
    load_dim: 5
    reduce_beams: 32
    type: LoadPointsFromFile
    use_dim: 5
  - load_augmented: null
    load_dim: 5
    pad_empty_sweeps: true
    reduce_beams: 32
    remove_close: true
    sweeps_num: 9
    type: LoadPointsFromMultiSweeps
    use_dim: 5
  - type: LoadAnnotations3D
    with_attr_label: false
    with_bbox_3d: true
    with_label_3d: true
  - bot_pct_lim:
    - 0.0
    - 0.0
    final_dim:
    - 256
    - 704
    is_train: false
    rand_flip: false
    resize_lim:
    - 0.48
    - 0.48
    rot_lim:
    - 0.0
    - 0.0
    type: ImageAug3D
  - is_train: false
    resize_lim:
    - 1.0
    - 1.0
    rot_lim:
    - 0.0
    - 0.0
    trans_lim: 0.0
    type: GlobalRotScaleTrans
  - classes:
    - drivable_area
    - ped_crossing
    - walkway
    - stop_line
    - carpark_area
    - divider
    dataset_root: data/nuscenes/
    type: LoadBEVSegmentation
    xbound:
    - -50.0
    - 50.0
    - 0.5
    ybound:
    - -50.0
    - 50.0
    - 0.5
  - point_cloud_range:
    - -51.2
    - -51.2
    - -5.0
    - 51.2
    - 51.2
    - 3.0
    type: PointsRangeFilter
  - mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
    type: ImageNormalize
  - classes:
    - car
    - truck
    - construction_vehicle
    - bus
    - trailer
    - barrier
    - motorcycle
    - bicycle
    - pedestrian
    - traffic_cone
    type: DefaultFormatBundle3D
  - keys:
    - img
    - points
    - gt_bboxes_3d
    - gt_labels_3d
    - gt_masks_bev
    meta_keys:
    - camera_intrinsics
    - camera2ego
    - lidar2ego
    - lidar2camera
    - camera2lidar
    - lidar2image
    - img_aug_matrix
    - lidar_aug_matrix
    type: Collect3D
fp16:
  loss_scale:
    growth_interval: 2000
gt_paste_stop_epoch: -1
image_size:
- 256
- 704
input_modality:
  use_camera: true
  use_external: false
  use_lidar: true
  use_map: false
  use_radar: false
load_augmented: null
load_dim: 5
load_from: null
log_config:
  hooks:
  - type: TextLoggerHook
  - type: TensorboardLoggerHook
  interval: 50
lr_config:
  policy: cyclic
map_classes:
- drivable_area
- ped_crossing
- walkway
- stop_line
- carpark_area
- divider
max_epochs: 20
model:
  codebook:
    codebook_beta: 1
    codebook_dim: 128
    codebook_size: 256
    decay: 0.99
    eps: 1e-5
    type: NormEMAVectorQuantizer
  decoder:
    attn_resolutions:
    - 16
    channels:
    - 512
    - 256
    - 256
    - 128
    image_channels: 6
    latent_dim: 128
    num_res_blocks: 3
    resolution: 16
    type: Decoder
  encoder:
    augment: 3
    channels:
    - 64
    - 128
    image_channels: 6
    latent_dim: 128
    type: SampleEncoderAutoAugment
  patch_size: 8
  type: CNNVQVAE
momentum_config:
  policy: cyclic
object_classes:
- car
- truck
- construction_vehicle
- bus
- trailer
- barrier
- motorcycle
- bicycle
- pedestrian
- traffic_cone
optimizer:
  lr: 0.0001
  paramwise_cfg:
    custom_keys:
      absolute_pos_embed:
        decay_mult: 0
      relative_position_bias_table:
        decay_mult: 0
  type: AdamW
  weight_decay: 0.01
optimizer_config:
  grad_clip:
    max_norm: 35
    norm_type: 2
point_cloud_range:
- -51.2
- -51.2
- -5.0
- 51.2
- 51.2
- 3.0
reduce_beams: 32
resume_from: null
run_dir: workdir/tmp
runner:
  max_epochs: 20
  type: CustomEpochBasedRunner
seed: 0
test_pipeline:
- to_float32: true
  type: LoadMultiViewImageFromFiles
- coord_type: LIDAR
  load_augmented: null
  load_dim: 5
  reduce_beams: 32
  type: LoadPointsFromFile
  use_dim: 5
- load_augmented: null
  load_dim: 5
  pad_empty_sweeps: true
  reduce_beams: 32
  remove_close: true
  sweeps_num: 9
  type: LoadPointsFromMultiSweeps
  use_dim: 5
- type: LoadAnnotations3D
  with_attr_label: false
  with_bbox_3d: true
  with_label_3d: true
- bot_pct_lim:
  - 0.0
  - 0.0
  final_dim:
  - 256
  - 704
  is_train: false
  rand_flip: false
  resize_lim:
  - 0.48
  - 0.48
  rot_lim:
  - 0.0
  - 0.0
  type: ImageAug3D
- is_train: false
  resize_lim:
  - 1.0
  - 1.0
  rot_lim:
  - 0.0
  - 0.0
  trans_lim: 0.0
  type: GlobalRotScaleTrans
- classes:
  - drivable_area
  - ped_crossing
  - walkway
  - stop_line
  - carpark_area
  - divider
  dataset_root: data/nuscenes/
  type: LoadBEVSegmentation
  xbound:
  - -50.0
  - 50.0
  - 0.5
  ybound:
  - -50.0
  - 50.0
  - 0.5
- point_cloud_range:
  - -51.2
  - -51.2
  - -5.0
  - 51.2
  - 51.2
  - 3.0
  type: PointsRangeFilter
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: ImageNormalize
- classes:
  - car
  - truck
  - construction_vehicle
  - bus
  - trailer
  - barrier
  - motorcycle
  - bicycle
  - pedestrian
  - traffic_cone
  type: DefaultFormatBundle3D
- keys:
  - img
  - points
  - gt_bboxes_3d
  - gt_labels_3d
  - gt_masks_bev
  meta_keys:
  - camera_intrinsics
  - camera2ego
  - lidar2ego
  - lidar2camera
  - camera2lidar
  - lidar2image
  - img_aug_matrix
  - lidar_aug_matrix
  type: Collect3D
train_pipeline:
- to_float32: true
  type: LoadMultiViewImageFromFiles
- coord_type: LIDAR
  load_augmented: null
  load_dim: 5
  reduce_beams: 32
  type: LoadPointsFromFile
  use_dim: 5
- load_augmented: null
  load_dim: 5
  pad_empty_sweeps: true
  reduce_beams: 32
  remove_close: true
  sweeps_num: 9
  type: LoadPointsFromMultiSweeps
  use_dim: 5
- type: LoadAnnotations3D
  with_attr_label: false
  with_bbox_3d: true
  with_label_3d: true
- db_sampler:
    classes:
    - car
    - truck
    - construction_vehicle
    - bus
    - trailer
    - barrier
    - motorcycle
    - bicycle
    - pedestrian
    - traffic_cone
    dataset_root: data/nuscenes/
    info_path: data/nuscenes/nuscenes_dbinfos_train.pkl
    points_loader:
      coord_type: LIDAR
      load_dim: 5
      reduce_beams: ${reduce_beams
      type: LoadPointsFromFile
      use_dim: 5
    prepare:
      filter_by_difficulty:
      - -1
      filter_by_min_points:
        barrier: 5
        bicycle: 5
        bus: 5
        car: 5
        construction_vehicle: 5
        motorcycle: 5
        pedestrian: 5
        traffic_cone: 5
        trailer: 5
        truck: 5
    rate: 1.0
    sample_groups:
      barrier: 2
      bicycle: 6
      bus: 4
      car: 2
      construction_vehicle: 7
      motorcycle: 6
      pedestrian: 2
      traffic_cone: 2
      trailer: 6
      truck: 3
  stop_epoch: -1
  type: ObjectPaste
- bot_pct_lim:
  - 0.0
  - 0.0
  final_dim:
  - 256
  - 704
  is_train: true
  rand_flip: true
  resize_lim:
  - 0.38
  - 0.55
  rot_lim:
  - -5.4
  - 5.4
  type: ImageAug3D
- is_train: true
  resize_lim:
  - 0.9
  - 1.1
  rot_lim:
  - -0.78539816
  - 0.78539816
  trans_lim: 0.5
  type: GlobalRotScaleTrans
- classes:
  - drivable_area
  - ped_crossing
  - walkway
  - stop_line
  - carpark_area
  - divider
  dataset_root: data/nuscenes/
  type: LoadBEVSegmentation
  xbound:
  - -50.0
  - 50.0
  - 0.5
  ybound:
  - -50.0
  - 50.0
  - 0.5
- type: RandomFlip3D
- point_cloud_range:
  - -51.2
  - -51.2
  - -5.0
  - 51.2
  - 51.2
  - 3.0
  type: PointsRangeFilter
- point_cloud_range:
  - -51.2
  - -51.2
  - -5.0
  - 51.2
  - 51.2
  - 3.0
  type: ObjectRangeFilter
- classes:
  - car
  - truck
  - construction_vehicle
  - bus
  - trailer
  - barrier
  - motorcycle
  - bicycle
  - pedestrian
  - traffic_cone
  type: ObjectNameFilter
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: ImageNormalize
- fixed_prob: true
  max_epoch: 20
  mode: 1
  offset: false
  prob: 0.0
  ratio: 0.5
  rotate: 1
  type: GridMask
  use_h: true
  use_w: true
- type: PointShuffle
- classes:
  - car
  - truck
  - construction_vehicle
  - bus
  - trailer
  - barrier
  - motorcycle
  - bicycle
  - pedestrian
  - traffic_cone
  type: DefaultFormatBundle3D
- keys:
  - img
  - points
  - gt_bboxes_3d
  - gt_labels_3d
  - gt_masks_bev
  meta_keys:
  - camera_intrinsics
  - camera2ego
  - lidar2ego
  - lidar2camera
  - camera2lidar
  - lidar2image
  - img_aug_matrix
  - lidar_aug_matrix
  type: Collect3D
use_dim: 5
voxel_size:
- 0.1
- 0.1
- 0.2
